//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public string Extention { get; set; }
        public int Type { get; set; }
        public int Category { get; set; }
        public int Status { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ApplicationUser_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
