//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorMessage
    {
        public int Id { get; set; }
        public System.DateTime DateError { get; set; }
        public string Message { get; set; }
        public string InnerException { get; set; }
        public string FileName { get; set; }
        public string MethodName { get; set; }
        public int Line { get; set; }
        public int Col { get; set; }
        public string StackTrace { get; set; }
    }
}
