//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogForSignalr
    {
        public int Id { get; set; }
        public int UserLog { get; set; }
        public int TransactionLog { get; set; }
        public int DocumentLog { get; set; }
        public int UserBankCardLog { get; set; }
        public int WithdrawLog { get; set; }
        public int VoucherLog { get; set; }
        public int TicketLog { get; set; }
        public int TetherLog { get; set; }
        public int VoucherWithoutAuthentication { get; set; }
    }
}
