//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentService()
        {
            this.PriceHistories = new HashSet<PriceHistory>();
        }
    
        public int Id { get; set; }
        public int CurrencyID { get; set; }
        public string Unit { get; set; }
        public string Title { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal SellPrice { get; set; }
        public Nullable<decimal> MinimumBuyVolume { get; set; }
        public Nullable<decimal> MinimumSellVolume { get; set; }
        public bool IsDisabled { get; set; }
        public decimal TransactionFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceHistory> PriceHistories { get; set; }
    }
}
