//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellVoucherWithoutAuthentication
    {
        public int Id { get; set; }
        public string Serial { get; set; }
        public string ActivationCode { get; set; }
        public double Volume { get; set; }
        public string BatchNum { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CardNumber { get; set; }
        public int Status { get; set; }
        public decimal TotalPrice { get; set; }
        public int StatusPayment { get; set; }
        public Nullable<int> Try { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> Bot { get; set; }
    }
}
