//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int TicketStatus { get; set; }
        public int TicketCategory { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
