//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public System.Guid TransactionGuid { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public decimal TotalPrice { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public int TransactionType { get; set; }
        public Nullable<int> PaymentWay { get; set; }
        public string RefrenceId { get; set; }
        public Nullable<int> ReciveType { get; set; }
        public Nullable<int> SaleType { get; set; }
        public int PaymentBatchNum { get; set; }
        public string ReciveWalletAddress { get; set; }
        public string VoucherActivationCode { get; set; }
        public string VoucherSerial { get; set; }
        public Nullable<int> WalleteId { get; set; }
        public int UserID { get; set; }
        public Nullable<int> PaymentServiceId { get; set; }
        public Nullable<int> UserBankCardId { get; set; }
        public Nullable<int> VoucherId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> TetherId { get; set; }
        public Nullable<decimal> PercentCommision { get; set; }
        public Nullable<int> ReferTransactionId { get; set; }
    
        public virtual Tether Tether { get; set; }
    }
}
