//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWallet
    {
        public int Id { get; set; }
        public int UserID { get; set; }
        public string WalletAddress { get; set; }
        public decimal WalletBalance { get; set; }
    }
}
