//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Tethers = new HashSet<Tether>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> LastLoggedIn { get; set; }
        public Nullable<int> TblState_Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string NationalCode { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public bool MobileIsConfirmed { get; set; }
        public string ReferId { get; set; }
        public string ReferIdMe { get; set; }
        public Nullable<System.DateTime> LastWithdraw { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<decimal> TotalUserLevelTransaction { get; set; }
        public Nullable<int> VerifiedDocumentID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public decimal PercentageCommission { get; set; }
        public bool UpdateUserCookieInNextRequest { get; set; }
        public string SignalRHubId { get; set; }
        public Nullable<System.DateTime> LastSignalRConnected { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int OldId { get; set; }
        public Nullable<int> PublicMessageCount { get; set; }
        public Nullable<int> LastMessageId { get; set; }
        public string ProviderKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tether> Tethers { get; set; }
    }
}
