//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdatePrice.Models.Entities.p01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdraw
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> UserBankCardId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Try { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> Bot { get; set; }
    }
}
